language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
script:
  - dotnet tool install --global coverlet.console --version 1.0
  - dotnet restore
  - dotnet build ./CloudTools-Assaigment/ -c Release
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_script:
  - bash <(curl -s https://codecov.io/bash)